export const OrderSchema = {
  type: 'object',
  properties: {
    id: { type: 'string', example: '507f1f77bcf86cd799439011' },
    customer_id: { type: 'string', example: '507f191e810c19729de860ea' },
    order_number: { type: 'string', example: 'ORD-123456' },
    order_type: { type: 'string', enum: ['pickup', 'delivery'], example: 'pickup' },
    service_time_type: { type: 'string', enum: ['ASAP', 'Schedule'], example: 'ASAP' },
    schedule_time: { type: 'string', format: 'date-time' },
    ready_time: { type: 'string', format: 'date-time' },
    actual_ready_time: { type: 'string', format: 'date-time' },
    status: {
      type: 'string',
      enum: [
        'pending',
        'accepted',
        'inkitchen',
        'ready',
        'out of delivery',
        'completed',
        'canceled',
      ],
      example: 'pending',
    },
    created_at: { type: 'string', format: 'date-time' },
    updated_at: { type: 'string', format: 'date-time' },
    cancelled_at: { type: 'string', format: 'date-time' },
    completed_at: { type: 'string', format: 'date-time' },
    cancelled_reason: { type: 'string' },
    cancelled_by: { type: 'string' },
    money: {
      type: 'object',
      properties: {
        subtotal: { type: 'number', example: 50.0 },
        discount: { type: 'number', example: 5.0 },
        delivery_fee: { type: 'number', example: 0.0 },
        tax_total: { type: 'number', example: 4.5 },
        tips: { type: 'number', example: 5.0 },
        total_amount: { type: 'number', example: 54.5 },
        currency: { type: 'string', example: 'USD' },
        payment: { type: 'string', example: 'Card' },
      },
    },
    delivery: {
      type: 'object',
      properties: {
        name: { type: 'string', example: 'John Doe' },
        phone: { type: 'string', example: '+1234567890' },
        address: { type: 'object', additionalProperties: true },
      },
    },
    notes: { type: 'string', example: 'Please include extra napkins.' },
    items: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          menu_item_id: { type: 'string' },
          size_id: { type: 'string' },
          name_snap: { type: 'string' },
          size_snap: { type: 'string' },
          unit_price: { type: 'number' },
          quantity: { type: 'number' },
          modifier_totals: { type: 'number' },
          line_subtotal: { type: 'number' },
          special_notes: { type: 'string' },
          modifiers: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                modifier_id: { type: 'string' },
                name_snapshot: { type: 'string' },
                modifier_quantity_id: { type: 'string' },
                quantity_label_snapshot: { type: 'string' },
                unit_price_delta: { type: 'number' },
              },
            },
          },
        },
      },
    },
  },
};
